import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NoiseOverlay from "./components/ui/NoiseOverlay";
import "./styles/globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="p-4 bg-gray-100 dark:bg-gray-800">
          <nav>
            <a href="/">Home</a> | <a href="/about">About</a> | <a href="/admin">Admin</a>
          </nav>
        </header>

        <main className="p-8">{children}</main>

        <footer className="p-4 bg-gray-100 dark:bg-gray-800 text-center">
          © 2025 Mi App
        </footer>
        <NoiseOverlay />
      </body>
    </html>
  );
}
