import type { Metadata } from "next";
import { Bangers, DM_Sans } from "next/font/google";
import NoiseOverlay from "./components/ui/NoiseOverlay";
import Image from 'next/image';
import "./styles/globals.css";

const bangers = Bangers({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bangers",
});

const dmSans = DM_Sans({
  weight: ["400", "600"],
  style: "normal",
  variable: "--font-dm-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Geekiverse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${bangers.variable} antialiased px-8`}
      >
        <header className="flex items-center p-4 bg-gray-100 border">
          <div className="relative w-40 aspect-[951/291]">
            <Image
                src="/Logo.png"
                alt="Geekiverse Logo"
                fill
                priority
                sizes="160px"
                className="object-contain"
            />
          </div>

          <div className="flex flex-row text-end">
            <button>Change</button>
            <div>Carrito</div>
          </div>
        </header>

        <main>{children}</main>

        <footer className="p-4 bg-gray-100 dark:bg-gray-800 text-center">
          © 2025 Mi App
        </footer>
        <NoiseOverlay />
      </body>
    </html>
  );
}
